import { useContext } from "react";

import { DrawerContext } from "@/stores/context/drawer";
import Head from "next/head";

const Layout = ({ title, children }) => {
  const { visible } = useContext(DrawerContext);
  return (
    <>
      <Head>
        <title>{title || "Create Next App"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={visible ? "fixed w-full h-full" : ""}>
        <section className="container">{children}</section>
      </main>
    </>
  );
};

export default Layout;
